var searchData=
[
  ['get_3c_20t_20_3e_0',['Get&lt; T &gt;',['../class_api_services_client.html#a4b88eee82f4fe31b2ba8878f79e861cd',1,'ApiServicesClient']]],
  ['getcustomerbyemail_1',['GetCustomerByEmail',['../class_gyminize___a_p_i_1_1_controllers_1_1_customer_controller.html#a2f94814066375525d5b0751cb252f98f',1,'Gyminize_API::Controllers::CustomerController']]],
  ['getcustomerbyid_2',['GetCustomerByID',['../class_gyminize___a_p_i_1_1_controllers_1_1_customer_controller.html#a2eaa94a54f50ead271827ed3afc2cbc1',1,'Gyminize_API::Controllers::CustomerController']]],
  ['getcustomerbyusername_3',['GetCustomerByUserName',['../class_gyminize___a_p_i_1_1_controllers_1_1_customer_controller.html#a77a94ebabce0c555f1f3c7c46c07d03e',1,'Gyminize_API::Controllers::CustomerController']]],
  ['getcustomerhealthbycustomerid_4',['GetCustomerHealthByCustomerId',['../class_gyminize___a_p_i_1_1_controllers_1_1_customerhealth_controller.html#a90aac26eca2cdf190f73c3a2290d09e7',1,'Gyminize_API::Controllers::CustomerhealthController']]],
  ['getting_20started_5',['Getting Started',['../md__c_1_2_users_2_hi_2_desktop_2_d_o___a_n___w_i_n_2_gyminize___win_ui___app_2_gyminize_8_tests_8_m_s_test_2_r_e_a_d_m_e.html#autotoc_md0',1,'']]],
  ['googleaigeminichatcompletionservice_6',['GoogleAIGeminiChatCompletionService',['../class_gyminize_1_1_services_1_1_google_a_i_gemini_chat_completion_service.html',1,'Gyminize::Services']]],
  ['guide1viewmodel_7',['Guide1ViewModel',['../class_gyminize_1_1_view_models_1_1_guide1_view_model.html',1,'Gyminize::ViewModels']]],
  ['guide2viewmodel_8',['Guide2ViewModel',['../class_gyminize_1_1_view_models_1_1_guide2_view_model.html',1,'Gyminize::ViewModels']]],
  ['guide3viewmodel_9',['Guide3ViewModel',['../class_gyminize_1_1_view_models_1_1_guide3_view_model.html',1,'Gyminize::ViewModels']]],
  ['guidepage1_10',['GuidePage1',['../class_gyminize_1_1_views_1_1_guide_page1.html',1,'Gyminize::Views']]],
  ['guidepage2_11',['GuidePage2',['../class_gyminize_1_1_views_1_1_guide_page2.html',1,'Gyminize::Views']]],
  ['guidepage3_12',['GuidePage3',['../class_gyminize_1_1_views_1_1_guide_page3.html',1,'Gyminize::Views']]],
  ['gyminize_13',['Gyminize',['../namespace_gyminize.html',1,'']]],
  ['gyminize_3a_3amodels_14',['Models',['../namespace_gyminize_1_1_models.html',1,'Gyminize']]],
  ['gyminize_3a_3aservices_15',['Services',['../namespace_gyminize_1_1_services.html',1,'Gyminize']]],
  ['gyminize_3a_3atests_16',['Tests',['../namespace_gyminize_1_1_tests.html',1,'Gyminize']]],
  ['gyminize_3a_3atests_3a_3amstest_17',['MSTest',['../namespace_gyminize_1_1_tests_1_1_m_s_test.html',1,'Gyminize::Tests']]],
  ['gyminize_3a_3atests_3a_3amstest_3a_3aviewmodel_18',['ViewModel',['../namespace_gyminize_1_1_tests_1_1_m_s_test_1_1_view_model.html',1,'Gyminize::Tests::MSTest']]],
  ['gyminize_3a_3aviewmodels_19',['ViewModels',['../namespace_gyminize_1_1_view_models.html',1,'Gyminize']]],
  ['gyminize_3a_3aviews_20',['Views',['../namespace_gyminize_1_1_views.html',1,'Gyminize']]],
  ['gyminize_5fapi_21',['Gyminize_API',['../namespace_gyminize___a_p_i.html',1,'']]],
  ['gyminize_5fapi_3a_3acontrollers_22',['Controllers',['../namespace_gyminize___a_p_i_1_1_controllers.html',1,'Gyminize_API']]],
  ['gyminize_5fapi_3a_3adata_23',['Data',['../namespace_gyminize___a_p_i_1_1_data.html',1,'Gyminize_API']]],
  ['gyminize_5fapi_3a_3adata_3a_3amodel_24',['Model',['../namespace_gyminize___a_p_i_1_1_data_1_1_model.html',1,'Gyminize_API::Data']]],
  ['gyminize_5fapi_3a_3adata_3a_3amodels_25',['Models',['../namespace_gyminize___a_p_i_1_1_data_1_1_models.html',1,'Gyminize_API::Data']]],
  ['gyminize_5fapi_3a_3adata_3a_3arepositories_26',['Repositories',['../namespace_gyminize___a_p_i_1_1_data_1_1_repositories.html',1,'Gyminize_API::Data']]]
];
